### ISSUE TITLE
Add views: shouldn't be possible to add non-existent views

### ISSUE THREAD

**Issue by yochannah** [intermine/InterMine-Data-Browser-Tool#23]
It looks like any free text is allowed in the add view dialogue :) 

![image](https://user-images.githubusercontent.com/9271438/51392855-1cf87000-1b2e-11e9-8835-0ade06c5a5b2.png)

**Comment by AdrianBZG** [comment]
Yep, will add a check!

**Comment by AdrianBZG** [comment]
Possible approach: fetch the current mine model and get the list of facets in an array. This needs to be done at the time the mine is loading and stored globally. Then, when the user adds a new view in the view manager, the text should coincide with one of the facets in the array, otherwise display warning.

**Comment by yochannah** [comment]
Do you think we could type-ahead, or allow selection from a list (remember,
it's aimed at naive usrs who many not know what columns to select)

**Comment by AdrianBZG** [comment]
@yochannah Yes, that would be better!

**Comment by AdrianBZG** [comment]
Already done by adding a select #28
