### ISSUE TITLE
"Location" Filter shows error

### ISSUE THREAD

**Issue by Zemotacqy** [intermine/InterMine-Data-Browser-Tool#25]
Whenever I select the Location filter and enter the following details:
Chromosome: 12
Start: 1 End: 1000
And when I press the GO button. I get the following error in the console:

> Uncaught TypeError: Cannot read property 'min' of undefined 
error at common.min.js file

**Comment by AdrianBZG** [comment]
@Zemotacqy Good point!

This happens because with that filter parameters, there are 0 results.

If you try for instance, Chromosome 12, Start 1 End 100000. Then you get results and no problem appears.

Maybe adding a warning message when that error happens, saying that there are no results, and resetting the constraint, would be helpful.

**Comment by Zemotacqy** [comment]
Ok @AdrianBZG . From where can I get the set of permissible values in the filter.

**Comment by AdrianBZG** [comment]
@Zemotacqy To do that for the case of the Location filter, you would need to query for all the available Start-End ranges and check which ones have values. This is very expensive and it's not desired.

I think that it's better if, since the im-table already shows a message when no values are available, to take the part where the min function is being used, and wrap it in an 'if' that checks whether the object is null or not... this will avoid errors and any malfunctioning of the interface.

What do you think? Could we do another workaround?
