### ISSUE TITLE
add windows setup guide

### ISSUE THREAD

**Issue by yochannah** [intermine/InterMine-Data-Browser-Tool#83]
this issue is for @officialkome - they've set up an amazing windows tutorial on wordpress in #78 but would like to convert it to markdown :)

**Comment by Officialkome** [comment]
Thanks for creating this issue @yochannah, I would get started as soon as it is assigned to me.

I tend to use markdown to re-write the tutorial, so that it is here on GitHub instead of directing to a remote site (WordPress in this case). 

This will make it even easier for contributors to access. 😁
